name = "VoxelModel"
uuid = "4956fa17-11d8-4a0b-a900-0a865cb13992"
authors = ["Jake W. Liu"]
version = "1.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PlotlyGeometries = "da4dd95e-df4f-4caf-ac06-cee3b0f5c2e6"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"

[compat]
julia = "1.8.0"
Combinatorics = "1"
PlotlyJS = "0.18"
PlotlyGeometries = "2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
